---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./longhorn/helmrelease.yaml
  - ./longhorn/storageclass.yaml
  - ./longhorn/minio-secret.sops.yaml
