---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vouch
  namespace: flux-system
spec:
  interval: 1h
  #url: https://halkeye.github.io/helm-charts
  url: https://vouch.github.io/helm-charts/
