---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: domoticz
  name: domoticz
  namespace: domoticz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domoticz
  template:
    metadata:
      labels:
        app: domoticz
    spec:
      hostNetwork: true
      volumes:
        - name: domoticz-storage
          persistentVolumeClaim:
            claimName: domoticz-storage-pvc
        - name: domoticz-local-path-storage
          persistentVolumeClaim:
            claimName: domoticz-local-path-storage
        - name: modbus-storage
          configMap:
            name: modbus-cm
      containers:
        - image: domoticz/domoticz:2023-beta.15082
          name: domoticz
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: LOG_PATH
              value: "/dev/null"
              # value: "/opt/domoticz/userdata/domoticz.log"
          volumeMounts:
            - mountPath: "/opt/domoticz/userdata"
              name: domoticz-storage
            - mountPath: "/opt/domoconfigseed/"
              name: domoticz-local-path-storage
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
        # - image: gkroone/clockbox:latest
        #   name: semodbus2domoticz
        #   volumeMounts:
        #     - mountPath: /domoticz.ini
        #       subPath: domoticz.ini
        #       name: modbus-storage
        #   resources:
        #     requests:
        #       cpu: "50m"
        #       memory: "32Mi"
        #     limits:
        #       cpu: "75m"
        #       memory: "64Mi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: modbus-cm
  namespace: domoticz
data:
  domoticz.ini: |
    [DOMOTICZ]
    # For Domoticz, please edit below to your own environment           #
    #####################################################################
    domoip =127.0.0.1
    # Domoticz ipaddress.
    dport =8080
    #Domoticz port number.
    idxSEstat = 3348
    # idx value of SolarEdge Status, Text device
    idxActPwr = 3356
    # idx value of SolarEdge Actual Power / Total Production, General, Kwh device
    idxActPwr2 = 3347
    # idx value of SolarEdge Actual Power / Total Production, General, Kwh device
    idxACinv = 3355
    # idx value of AC Inverter, Voltage device
    idxac_i = 3350
    # idx value of AC Inverter, Amp device
    idxAC_f = 3358
    # idx value of AC Inverter freqency text device
    idxDCinv = 3351
    # idx value of DC Inverter, Voltage device
    idxdc_i = 3357
    # idx value of DC Inverter, Amp device
    idxEffin = 3352
    # idx value of SolarEdge Efficiency, Percentage device
    idxTemp  = 3353
    # idx value of SolarEdge Temperature, Temperature device
    idxTotPwr = 3354
    # idx value of Total LifTime Production, Custom Sensor

    ######################################################################
    # Domoticz extra variables  used                                     #
    ######################################################################
    version ="1.2"
    url =""
    content=""
    dwh=0
    deff=0
    dtemp=0
    dac_f=0
---


apiVersion: v1
kind: Service
metadata:
  name: domoticz
  namespace: domoticz
spec:
  selector:
    app: domoticz
  ports:
    - protocol: TCP
      port: 8080
      name: http
