---
kind: StorageClass
apiVersion: storage.k8s.io/v1
# Annotations:
#   longhorn.io/last-applied-configmap=kind: StorageClass
metadata:
  name: longhorn2
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Delete"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "disabled"
