---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secrets.sops.yaml
  - ./release.yaml
patches:
- patch: '[{"op": "replace", "path": "/spec/values/image", "value": "https://hub.docker.com/r/voucher/vouch-proxy"}]'
  target:
    kind: HelmRelease
    name: vouch
    namespace: networking