---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vouch
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: vouch
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: vouch
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 4
  upgrade:
    remediation:
      retries: 4
  values:
    existingSecretName: vouchsecrets
    replicaCount: 1
    ingress:
      # main:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        # external-dns.alpha.kubernetes.io/target: vouch.mykubelab.com
        hajimari.io/icon: account-check
      hosts:
        - "vouch.${SECRET_DOMAIN}"
      tls:
        - secretName: tls-mykubelab.com
          hosts:
            - "vouch.${SECRET_DOMAIN}"

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
