---
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# namespace: domoticz
# resources:
#   - ../base/domoticz
# # patches:
# #   - path: podinfo-values.yaml
# #     target:
# #       kind: HelmRelease
# ---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - ../base/podinfo
  - ../base/domoticz
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
